### PR TITLE
Iteration2 add entry

### PR DESCRIPTION
**Pull request by niichapats**

### CODE REVIEW

**Comment by ParimaSA** [comment]
I this two urls should not pass the business_id since we can check the business by the user.
- path('home/<int:business_id>/', views.home, name='home'),
- path('add_customer/<int:business_id>/', views.add_customer, name='add_customer'),

Then you need to rewrite this function, change from find the business by id to find it by user.

def add_customer(request):
    """Add a customer to a specific business and queue."""
    this_user = request.user
    business = Business.objects.get(user=this_user)
    queues = Queue.objects.filter(business=business) # what if business has 0 queue

I think it may be better if you use try-except, and when there is no queue(Queue.DoesNotExist) redirect the page to home.

**Comment by Thanchida** [comment]
I think you should delete 0005_alter_entry_time_out.py and create migrations after merge.

**Comment by niichapats** [comment]
> I this two urls should not pass the business_id since we can check the business by the user.
> 
> * path('home/int:business_id/', views.home, name='home'),
> * path('add_customer/int:business_id/', views.add_customer, name='add_customer'),
> 
> Then you need to rewrite this function, change from find the business by id to find it by user.
> 
> def add_customer(request): """Add a customer to a specific business and queue.""" this_user = request.user business = Business.objects.get(user=this_user) queues = Queue.objects.filter(business=business) # what if business has 0 queue
> 
> I think it may be better if you use try-except, and when there is no queue(Queue.DoesNotExist) redirect the page to home.

I've updated the URLs to remove business_id, modified add_customer to find the business by user, and added try-except to handle the no queue case.

**Comment by niichapats** [comment]
> I think you should delete 0005_alter_entry_time_out.py and create migrations after merge.

I've deleted 0005_alter_entry_time_out.py.

**Comment by Thanchida** [comment]
I think the login_required decorator is not being used; maybe you could delete it.

**Pull request merged**
